### ISSUE TITLE
Avoid using T1(...)

### ISSUE THREAD

**Issue by GiggleLiu** [ZKSI/QuantumInformation.jl#57]
1. It breaks for diagonal matrices input, because types does not always have constructors (basically means, better never use `typeof(obj)(...)`).
2. It allocates
```julia
julia> m = randn(1000,1000);

julia> @allocated convert(typeof(m),m)
0

julia> @allocated typeof(m)(m)
8000080
```

3. Do we really need interfaces like `DinamicalMatrix{T1}(m::T2)`? Or `DinamicalMatrix(m::T2)` is sufficient?

If you agree, I can submit a PR.

**Comment by pgawron** [comment]
Ad. 1, 2: Thanks for PR. Merged.

Ad 3. I wanted to have a flexible interface, in order to deal with situation where matrices are of different type. But it might be an overkill.

**Comment by GiggleLiu** [comment]
Cool, that makes sense. QuantunInformations.jl is a reliable package, learnt a lot from it. I wrote a blog for porting Yao.jl and QuantumInformations.jl https://giggleliu.github.io/yao_port_qi.html

**Comment by GiggleLiu** [comment]
Maybe close this issue?
