### ISSUE TITLE
Default Matrix type for IdentityChannel

### ISSUE THREAD

**Issue by adamglos92** [ZKSI/QuantumInformation.jl#79]
Matrix type for `IdentityChannel` defaults to `Matrix`. Maybe `SparseMatrixCSC` could be considered instead? Otherwise functions like `kron(id, u)`  will convert the final matrix to `Matrix` instead of sparse type by default irrespectively whether `u` is sparse or not.

**Comment by lpawela** [comment]
Sparse matrices are currently not supported. We plan to support them in `v0.7`
